### ISSUE TITLE
placeholder for text block

### ISSUE THREAD

**Issue by lbresler** [chamaileon-sdk/sdk-locales#14]
Is it possible to translate the placeholders :

Text block : "Double click to edit text!"
Button : "Click hete to edit me"
Image : "Double click to change image"

**Comment by lbresler** [comment]
I've find for text and button in the elementDefaults setting.

But not for the image.
the placeholder is here : 
![](https://cdn.chamaileon.io/assets/img/image_placeholder.png)

The setting staticAssetsBaseUrl doesn't seems to work.

**Comment by lacee677** [comment]
Hello.
Sorry for the delayed response.

Can you show me an example how you tried to use the `staticAssetsBaseUrl` config? As far as we're aware this config should work as it should.

Also you can check it and try it out in our playground and see if it works there:
https://sdk-playground.chamaileon.io/emaileditor#settings

**Comment by lbresler** [comment]
It was a misspeling on our side on the variable, sorry
