### ISSUE TITLE
Translation of the blocks addon

### ISSUE THREAD

**Issue by lbresler** [chamaileon-sdk/sdk-locales#22]
Hello,

Il is possible to translate "Warning" and "Cancel" when we delete a block ? I don't see these string in the translation file.

![image](https://github.com/chamaileon-sdk/sdk-locales/assets/27861892/35ad3b7f-f08f-4b39-ba7e-cc30e0e7bb59)

**Comment by lacee677** [comment]
Solved by https://github.com/chamaileon-sdk/sdk-locales/pull/24
