### ISSUE TITLE
Updates are lost when the user is too speedly

### ISSUE THREAD

**Issue by lbresler** [chamaileon-sdk/sdk-locales#32]
Sometimes, users make a modification before the editor is fully loaded.

Here is an exemple with the HTML Code box, that is opened before the "Loading..." message (the small reload after the first rendering) :

![image](https://github.com/chamaileon-sdk/sdk-locales/assets/27861892/a816fc22-b097-4ce5-8239-f79462f44cb0)

In this case, all changes are lost.

Is it possible to avoid any modification before the editor is fully loaded ?

**Comment by lacee677** [comment]
@lbresler In the future if the issue is not translation related please send an email to sdk@chamaileon.io instead of reporting it here.

**Comment by lacee677** [comment]
Hi.
Sorry for the late reply for the issue itself.

Do you use the provided splashScreen hooks for the plugin to overlay the plugin itself while you load the data in?
You can await the updateData and updateSettings methods and only hide the splashScreen when both of them finished. This should prevent the user in manipulating an email that is not fully loaded yet (or when an old one is still loaded into the plugin)
