### ISSUE TITLE
string missing

### ISSUE THREAD

**Issue by lbresler** [chamaileon-sdk/sdk-locales#7]
on the image editor in the gallery, some string are missing for localization : 

custom, square, landscape, , rotate, flip x, flip y, downscale

https://share.cleanshot.com/DaH7Y7

**Comment by lacee677** [comment]
Hello.
We updated our gallery plugin to support the translation of those texts as well.
You can find them here in the .json file: https://github.com/chamaileon-sdk/sdk-locales/blob/master/gallery/fr.json#L58
